print('----- Bem vindo a Passos Serviços S.A -----')
nome = input('Digite o Nome do Serviço: ')
produto = float(input('Digite o valor do Serviço R$:'))
credito = produto + (produto * 6.67 / 100)
debito = produto - (produto * 8 / 100)
pix = produto - (produto * 12 / 100)
print('Serviço de {},  valor R$:{}'.format(nome,produto))
print('Pagamento a prazo o serviço {}, fica com valor de R$:{:.2f} com juros'.format(nome,credito))
print('Pagamento a vista o serviço {}, fica com o valor de R$:{:.2f} com desconto'.format(nome,debito))
print('Pagamento no PIX o serviço {}, fica com o valor de R$:{:.2f} com desconto'.format(nome,pix))